export const MODE_FORMAT = "format";
export const MODE_VET = "vet";
export const MODE_RUN = "run";
export const MODE_CHECK = "check";
export const MONACO_DARK = "notebook-dark";
export const MONACO_LIGHT = "notebook-light";
export const FONT_NOTEBOOK = "Itim, cursive";
export const EDITOR_LANG = "go";
export const RUN_FAILS_BEFORE_HINT = 3;
